Match User ocr-tunnel
    AuthenticationMethods publickey
    PasswordAuthentication no
    KbdInteractiveAuthentication no
    AllowTcpForwarding remote
    PermitListen 172.17.0.1:19100
    GatewayPorts clientspecified
    PermitTTY no
    X11Forwarding no
    PermitTunnel no

Match all
