package com.bakapiano.maiscorehub.android.wechat;

import android.content.Intent;

import java.net.URI;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;

/**
 * Opens a narrowly-scoped OAuth URL in WeChat's own WebView through the
 * exported LauncherUI handoff.
 *
 * <p>WeChat 8.0.68 reads a serialized {@code start_ui_params} value from the
 * {@code intent_params_b} extra. Accepted targets are the local manual-launch
 * fallback and the exact WeChat OAuth entry generated by DXNET.</p>
 */
public final class WechatWebViewLauncher {
    private static final String WECHAT_PACKAGE = "com.tencent.mm";
    private static final String WECHAT_LAUNCHER = "com.tencent.mm.ui.LauncherUI";
    private static final String WECHAT_WEBVIEW =
            "com.tencent.mm.plugin.webview.ui.tools.WebViewUI";
    private static final String START_UI_PARAMS_EXTRA = "intent_params_b";
    private static final String LOCAL_PROXY_HOST = "10.77.0.2";
    private static final String WECHAT_OAUTH_HOST = "open.weixin.qq.com";
    private static final String WECHAT_OAUTH_PATH = "/connect/oauth2/authorize";
    private static final String CALLBACK_PREFIX =
            "http://tgk-wcaime.wahlap.com/wc_auth/oauth/callback/";

    private WechatWebViewLauncher() {
    }

    public static Intent createIntent(String launchUrl) {
        requireWechatLaunchUrl(launchUrl);
        return new Intent()
                .setClassName(WECHAT_PACKAGE, WECHAT_LAUNCHER)
                .addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_ACTIVITY_CLEAR_TOP)
                .putExtra(START_UI_PARAMS_EXTRA, buildStartUiParams(launchUrl));
    }

    static String buildStartUiParams(String launchUrl) {
        requireWechatLaunchUrl(launchUrl);
        return "<start_ui_params>"
                + "<activity>" + WECHAT_WEBVIEW + "</activity>"
                + "<extra_key>rawUrl</extra_key>"
                + "<extra>" + escapeXml(launchUrl) + "</extra>"
                + "</start_ui_params>";
    }

    static void requireWechatLaunchUrl(String launchUrl) {
        try {
            URI uri = URI.create(launchUrl);
            if (!isLocalManualLaunch(uri) && !isSecureWechatOAuth(uri)) {
                throw unexpectedLaunchUrl();
            }
        } catch (RuntimeException error) {
            if (error instanceof IllegalArgumentException
                    && "Unexpected WeChat launch URL".equals(error.getMessage())) {
                throw error;
            }
            throw new IllegalArgumentException("Invalid WeChat launch URL", error);
        }
    }

    private static boolean isLocalManualLaunch(URI uri) {
        return "http".equalsIgnoreCase(uri.getScheme())
                && LOCAL_PROXY_HOST.equalsIgnoreCase(uri.getHost())
                && uri.getPort() > 0
                && "/launch".equals(uri.getPath())
                && queryValue(uri.getRawQuery(), "nonce") != null;
    }

    private static boolean isSecureWechatOAuth(URI uri) {
        String redirectUri = queryValue(uri.getRawQuery(), "redirect_uri");
        String appId = queryValue(uri.getRawQuery(), "appid");
        String responseType = queryValue(uri.getRawQuery(), "response_type");
        String state = queryValue(uri.getRawQuery(), "state");
        return "https".equalsIgnoreCase(uri.getScheme())
                && WECHAT_OAUTH_HOST.equalsIgnoreCase(uri.getHost())
                && (uri.getPort() == -1 || uri.getPort() == 443)
                && uri.getUserInfo() == null
                && WECHAT_OAUTH_PATH.equals(uri.getPath())
                && appId != null
                && !appId.isBlank()
                && "code".equals(responseType)
                && state != null
                && !state.isBlank()
                && redirectUri != null
                && redirectUri.startsWith(CALLBACK_PREFIX);
    }

    private static String queryValue(String rawQuery, String name) {
        if (rawQuery == null || rawQuery.isBlank()) {
            return null;
        }
        for (String pair : rawQuery.split("&")) {
            int separator = pair.indexOf('=');
            String rawName = separator < 0 ? pair : pair.substring(0, separator);
            if (!name.equals(URLDecoder.decode(rawName, StandardCharsets.UTF_8))) {
                continue;
            }
            String rawValue = separator < 0 ? "" : pair.substring(separator + 1);
            return URLDecoder.decode(rawValue, StandardCharsets.UTF_8);
        }
        return null;
    }

    private static IllegalArgumentException unexpectedLaunchUrl() {
        return new IllegalArgumentException("Unexpected WeChat launch URL");
    }

    private static String escapeXml(String value) {
        return value
                .replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;")
                .replace("'", "&apos;");
    }
}
